sudo: required

services:
  - docker

before_script:
  - docker build --tag matchmaker .
  - docker run --name db --publish 5433:5432 --detach siggame/colisee-db

script:
  - docker run -e POSTGRES_HOST=db matchmaker npm run test

after_script:
  - docker stop db