sudo: required

services:
  - docker

language: nodejs

env:
  - POSTGRES_HOST=127.0.0.1:5433

before_script:
  - npm run setup
  - docker run --name matchmaker-db --publish 5433:5432 --detach siggame/colisee-db

script:
  - npm run test

after_script:
  - docker stop matchmaker-db